name: Server

on: [push, pull_request]

jobs:
  gradle-build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:7
        ports:
          - '27017-27019:27017-27019'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
